#!/usr/bin/env python3
"""Build browser library data and review HTML from editable CSV sources."""

from __future__ import annotations

import csv
import html
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
FOOD_CSV = HERE / "food_library.csv"
GYM_CSV = HERE / "gym_library.csv"
GENERATED_JS = HERE / "generated_libraries.js"
FOOD_HTML = HERE / "food_library.html"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def build_js(food_rows: list[dict[str, str]], gym_rows: list[dict[str, str]]) -> str:
    food_cols = list(food_rows[0].keys())
    food_lines = [",".join(food_cols)]
    for row in food_rows:
      food_lines.append(",".join(csv_escape(row.get(col, "")) for col in food_cols))

    activities = []
    variants = {}
    for row in gym_rows:
        name = row["name"].strip()
        kind = row.get("kind", "weight").strip() or "weight"
        group = row["group"].strip()
        activities.append({"group": group, "kind": kind, "name": name})
        type_values = [v.strip() for v in row.get("types", "").split("|") if v.strip()]
        if type_values:
            variants[name] = type_values

    return (
        "// Generated by dev/lib/build_libraries.py. Edit CSV sources, not this file.\n"
        "(function () {\n"
        f"  window.FITLOG_HOST_FOOD_LIBRARY_CSV = {json.dumps(chr(10).join(food_lines), ensure_ascii=False)};\n"
        f"  window.FITLOG_HOST_GYM_ACTIVITIES = {json.dumps(activities, ensure_ascii=False, indent=2)};\n"
        f"  window.FITLOG_HOST_GYM_VARIANTS = {json.dumps(variants, ensure_ascii=False, indent=2)};\n"
        "}());\n"
    )


def csv_escape(value: str) -> str:
    out = str(value or "")
    if any(ch in out for ch in [",", '"', "\n", "\r"]):
        out = '"' + out.replace('"', '""') + '"'
    return out


def build_food_html(rows: list[dict[str, str]]) -> str:
    cols = list(rows[0].keys())
    head = "".join(f"<th>{html.escape(col)}</th>" for col in cols)
    body_rows = []
    for row in rows:
        cells = "".join(f"<td>{html.escape(row.get(col, '')) or '&nbsp;'}</td>" for col in cols)
        body_rows.append(f"<tr>{cells}</tr>")
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FitLog Food Library Source</title>
  <style>
    body {{ margin: 0; font: 13px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #f5f7fb; color: #172033; }}
    .wrap {{ max-width: 1500px; margin: 0 auto; padding: 20px; }}
    h1 {{ margin: 0 0 4px; font-size: 20px; }}
    p {{ margin: 0 0 14px; color: #5f6b85; }}
    .table-shell {{ overflow: auto; max-height: calc(100vh - 96px); border: 1px solid #d8e0ee; background: #fff; border-radius: 8px; }}
    table {{ width: 100%; min-width: 1100px; border-collapse: collapse; }}
    th {{ position: sticky; top: 0; background: #f9fbff; color: #5f6b85; text-align: left; font-size: 12px; padding: 10px; border-bottom: 1px solid #d8e0ee; white-space: nowrap; }}
    td {{ padding: 8px 10px; border-bottom: 1px solid #edf1f7; vertical-align: top; }}
    tr:nth-child(even) {{ background: #fcfdff; }}
  </style>
</head>
<body>
  <div class="wrap">
    <h1>FitLog Food Library Source</h1>
    <p>{len(rows)} rows. Generic raw-food, rice/noodle, rolled oats, and restaurant rows are excluded.</p>
    <div class="table-shell">
      <table>
        <thead><tr>{head}</tr></thead>
        <tbody>{''.join(body_rows)}</tbody>
      </table>
    </div>
  </div>
</body>
</html>
"""


def main() -> None:
    food_rows = read_csv(FOOD_CSV)
    gym_rows = read_csv(GYM_CSV)
    GENERATED_JS.write_text(build_js(food_rows, gym_rows), encoding="utf-8")
    FOOD_HTML.write_text(build_food_html(food_rows), encoding="utf-8")


if __name__ == "__main__":
    main()
